### ISSUE TITLE
PSM - Explorere does not exist

### ISSUE THREAD

**Issue by alanmilinovic** [cyberark/CYBRHardeningCheck#20]
When verifying PSM Drivers it complains that Explorer doesn't exist:
![image](https://user-images.githubusercontent.com/1752983/102983321-2f466a00-450c-11eb-8861-ec74ae9459e1.png)

Tested on Windows Server 2019, PSM 11.7

**Comment by itsmegb** [comment]
The "Policies\Explorer does not exist" error is expected, it just means that the HideLocalDrives.ps1 script in the PSM\InstallationAutomation\Hardening folder has not been run against those users or manually Drive hardening has not been applied.

This causes the HidePSMDrives stage to return a warning/failure (i forget which), but i believe this to be expected behaviour.

**Comment by amilino** [comment]
If this is ok, I guess we can close the issue?
